# Site settings
title: Journey of Learning to Code
header-img: img/home-bg.png
email: brandonchin@me.com
copyright_name: bchinherein
description: > # this means to ignore newlines until "baseurl:"
  My personal experiences of the ups and downs of my career switch
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  bchinherein
learn_profile: bchinherein
email_username: brandonchin@me.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
